### ISSUE TITLE
Game softlocks after inputting filename.

### ISSUE THREAD

**Issue by rjoken** [suicvne/DOR_Remake#2]
Pressed space to enter a name, entered the name, then pressed enter. Game softlocks - can't navigate to starter deck selection or press space again to re-enter name etc.
Happens every time I input a name.

[Player.log](https://github.com/suicvne/DOR_Remake/files/6469095/Player.log)
![Screenshot showing the problem](https://user-images.githubusercontent.com/17675149/118044844-12052180-b36f-11eb-91d7-47550c8b0651.png)

Additional information:
Client version: 0.6.8.1 win x86_64
OS: Windows 7 Ultimate x86_64
Specs: Ryzen 5 1400, nVidia GTX 950, 32gb ram blah

**Comment by suicvne** [comment]
Thanks for the bug report! 

That’s a bit of a strange bug, I was just messing around in that screen today and didn’t notice any bugs there. It could be platform specific? Either way, looking into it!

Expect a fix tonight or tomorrow morning

**Comment by suicvne** [comment]
Wasn't able to replicate on macOS Big Sur, trying to get a sane Windows installation once again so I can test proper

**Comment by suicvne** [comment]
For once, I'm having a lot of trouble *finding* a Windows computer that actually works.

I attempted a fix anyway based on what I could gather from the logs. Please let me know if this works for you, thanks!

0.6.8.2a From Itch.io: https://ignoresolutions.itch.io/yu-gi-oh-duelists-of-the-roses-remake-beta
So far, it's only been uploaded for Windows as Mac and Linux do not have this bug present.

**Comment by rjoken** [comment]
Fixed. Now that it is, prepare for billions more bug reports >:)
