### ISSUE TITLE
Attacking an enemy deck leader directly softlocks game

### ISSUE THREAD

**Issue by rjoken** [suicvne/DOR_Remake#7]
![image](https://user-images.githubusercontent.com/17675149/118379628-8fc96700-b5d3-11eb-950a-e27604dc91e2.png)
Game enters inescapable state upon attacking directly. Can move cursor but not much else. Going to assume not implemented but could be platform specific, don't know.

[Player.log](https://github.com/suicvne/DOR_Remake/files/6488348/Player.log)
Additional information:
Client version: 0.6.8.2a win x86_64
OS: Windows 7 Ultimate x86_64
Specs: Ryzen 5 1400, nVidia GTX 950, 32gb ram

**Comment by suicvne** [comment]
This is ***very*** strange as this is one of those bugs I swore I knocked out before releasing it!!! 

I do have two questions:

1. What game mode?

2. Is it true that the battle animation completed successfully and "froze" after? As in UI was never restored?

The description that I give in #2 is what I'm interpreting from the log. The exception logged:

```
Exception in MessageHandler: NullReferenceException Object reference not set to an instance of an object
  at IgnoreSolutions.DuelistsOfTheRoses.Manager.DORGameManager.UserCode_CmdSendCardToGraveyard (System.UInt32 cardNetID) [0x00011] in <82940419b2244e21904c056b3bffffa1>:0 
  at IgnoreSolutions.DuelistsOfTheRoses.Manager.DORGameManager.InvokeUserCode_CmdSendCardToGraveyard (Mirror.NetworkBehaviour obj, Mirror.NetworkReader reader, Mirror.NetworkConnectionToClient senderConnection) [0x00022] in <82940419b2244e21904c056b3bffffa1>:0 
```

Looks like it crashed because the DORGameManager tried to send the DeckLeader to the graveyard. Oops. Easy enough fix.

**Comment by suicvne** [comment]
#5, #6, #7 are all on my target for Monday.

**Comment by rjoken** [comment]
> I do have two questions:
> 
>     1. What game mode?
Multiplayer VS 2P (myself, same client, forget what you actually call it. you know what i mean - i was controlling P1 with keyboard and P2 with controller)
Also occurred VS AI
 I haven't done any online testing as of yet.

>     2. Is it true that the battle animation completed successfully and "froze" after? As in UI was never restored?
Yes, precisely!

**Comment by suicvne** [comment]
This crash is *technically* fixed now, but I'm fighting with a separate issue now that's requiring me to add a feature to my animation sync.

**Comment by suicvne** [comment]
0.6.8.3 released on itch.io!

https://ignoresolutions.itch.io/yu-gi-oh-duelists-of-the-roses-remake-beta
